### ISSUE TITLE
Unable to publish to ArcGIS Enterprise 10.6

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/photo-survey#83] opened 2017-11-02 14:03 UTC
When I tried to publish to ArcGIS Enterprise 10.6 (https://rpubss120054.ags.esri.com/portal/home/signin.html - username: sharing1 password: sharing1) I receive the following error message, 00241 Field SHAPE_Length is not supported as display field. 
![image](https://user-images.githubusercontent.com/2781011/32329837-9994b5a0-bfb4-11e7-8d54-13717d73ee04.png)

Below are the settings I used when trying to publish the feature layer.
![image](https://user-images.githubusercontent.com/2781011/32329975-f453461e-bfb4-11e7-9555-97fba7a23ff8.png)

I'm assuming a user would run in to this issue when using ArcGIS Enterprise 10.5 or Portal for ArcGIS 10.4.

**Comment by ChrisBuscaglia** [comment] 2017-11-02 15:40
@HeatherEisan what version of Pro?

**Comment by HeatherEisan** [comment] 2017-11-02 15:50
@ChrisBuscaglia: I think this is user error. I accidentally included the Parcel feature class when trying to publish the feature layer. Once I removed it from the Pro project, the error went away.

**Comment by ChrisBuscaglia** [comment] 2017-11-02 15:55
@HeatherEisan Cannot reproduce, haven't had issues here before...
![capture](https://user-images.githubusercontent.com/5614261/32336084-920d1e66-bfab-11e7-9e65-527ed49ccc34.PNG)

**Comment by ChrisBuscaglia** [comment] 2017-11-02 16:14
closing

**Closed by ChrisBuscaglia** 2017-11-02 16:14 UTC
Labels: Holistic Feedback
